# -*- coding: utf-8 -*-
"""Pandas的基本操作.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IolW9RUrR2lGOeoFZQfq67jgxy6NYBgZ
"""

import pandas as pd


def pandas_test1():
    input_data = 'Resources/housing.csv'
    df = pd.read_csv(input_data, lineterminator='\n')

    for i in range(0, 10):
        df = df.append(df)

    print(df.shape)
    df.to_csv('/Users/yzhao/Downloads/housing_10.csv')


if __name__ == '__main__':
    pandas_test1()
